Add way management
vlnt-trsv/service-sale-tickets-test pull request #59
Opened 2024-09-18 16:48 UTC by Bakugan74

2024-09-18 17:08 UTC, vlnt-trsv requested changes

2024-09-18 17:08 UTC, vlnt-trsv commented on src/app/@types/index.d.ts
Обязательно исправь на структурированный вариант

2024-09-18 17:08 UTC, vlnt-trsv commented on src/pages/home/components/headerPanel/HeaderPanel.module.scss
Тогда оставь outline тоже

2024-09-18 17:08 UTC, vlnt-trsv commented on src/pages/home/components/mainPanel/child/wayManagement/wayInformation/WayInformation.tsx
Очень большой объем. В фиксе добавим конфигурационный файл

2024-09-18 17:08 UTC, vlnt-trsv commented on src/shared/api/queries.ts
> +      { id: 1, status: "free", documentSeria: "1234", documentNumber: "123456", price: 1276, tariff: 1000, duty: 50, dateSale: "26 сентября", whoSold: "Кассир Иванова А.И." },
Потом объяснишь, почему сюда записал остальные поля.

2024-09-18 17:08 UTC, vlnt-trsv commented on src/shared/ui/input/Input.module.scss
> +  width: 100%;
Убери, в нас fullwidth есть

2024-09-18 17:08 UTC, vlnt-trsv commented on src/shared/ui/table/Table.tsx
> +      pageSize = 100,
Верни 5, это дефолт

Если надо 100, то ставишь к компоненте при использование таблицы

2024-09-18 17:09 UTC, vlnt-trsv commented on src/app/@types/index.d.ts
Можно в следующем фиксе

2024-09-18 17:09 UTC, vlnt-trsv commented on src/pages/home/components/mainPanel/child/wayManagement/wayInformation/WayInformation.tsx
Можно в следующем фиксе

2024-09-19 15:27 UTC, Bakugan74 commented on src/pages/home/components/headerPanel/HeaderPanel.module.scss
?

2024-09-19 15:30 UTC, vlnt-trsv commented on src/pages/home/components/headerPanel/HeaderPanel.module.scss
Ну ты убрал outline и добавил border, оставь тогда outline тоже

2024-09-19 15:45 UTC, vlnt-trsv submitted a review, later dismissed

2024-09-20 11:52 UTC, vlnt-trsv approved these changes

2024-09-20 11:53 UTC, merged